---
title: "Analysis of the effects of the weather events on public health and economics accros the United States"
output: html_document
---

## Synopsis

Wheater events may have a big impact on the public health and economics. The goal of this analysis is to explore the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database and answer the questions which types of events are most harmful with respect to population health and have the greatest economic consequences. The NOAA database tracks characteristics of major storms and weather events in the United States from 1950 to 2011, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.

## Exploring the data

### Loading the data

The data for this analysis can be downloaded from the following locations :

* [Storm Data](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2) [bzip2]
* [National Weather Service Storm Data Documentation](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf)
* [National Climatic Data Center Storm Events FAQ](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2FNCDC%20Storm%20Events-FAQ%20Page.pdf)

```{r}
url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
  
if (!file.exists("./data/StormData.csv.bz2")) {
  dir.create("data")
  download.file(url, destfile = "StormData.csv.bz2", method="curl")
  bunzip2 ("StormData.csv.bz2", overwrite=TRUE, remove=FALSE, destname="StormData.csv")
  dateDownloaded <- date()
  stormdata <- read.csv ("StormData.csv", header=TRUE, stringsAsFactors=FALSE)
}
```
